# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "tasks" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"label" VARCHAR NOT NULL,"created" TIMESTAMP NOT NULL);

# --- !Downs

drop table "tasks";

